version: "3.8"
services:
  api:
    container_name: "site-api"
    build:
      context: "."
    ports:
      - "8000:8000"
    volumes:
      - ./src/site_api:/project/site_api
    networks:
      - "traveling"

networks:
  traveling:
    external: True
